const {
    NEXT_PUBLIC_DISQ,
    NEXT_PUBLIC_MEASUREMENT_ID,
    NEXT_PUBLIC_EDITOR_KEY,
    NEXT_PUBLIC_API_CLOUDIMARY,
    NEXT_PUBLIC_CLOUDINARY_APIKEY,
    NEXT_PUBLIC_CLOUDINARY_APISECRET,
    NEXT_PUBLIC_CLOUD_NAME,
    NEXT_PUBLIC_UPLOAD_PRESET,
    NEXT_PUBLIC_UPLOAD_POST_IMAGE,
    NEXT_PUBLIC_UPLOAD_PERFIL_PRESET,
    NEXT_PUBLIC_PUBLIC_VAPID_KEY,
} = process.env;

const env = {
    DISQ: NEXT_PUBLIC_DISQ,
    MEASUREMENT_ID: NEXT_PUBLIC_MEASUREMENT_ID,
    EDITOR_KEY: NEXT_PUBLIC_EDITOR_KEY,
    API_CLOUDIMARY: NEXT_PUBLIC_API_CLOUDIMARY,
    CLOUDINARY_APIKEY: NEXT_PUBLIC_CLOUDINARY_APIKEY,
    CLOUDINARY_APISECRET: NEXT_PUBLIC_CLOUDINARY_APISECRET,
    CLOUD_NAME: NEXT_PUBLIC_CLOUD_NAME,
    UPLOAD_PRESET: NEXT_PUBLIC_UPLOAD_PRESET,
    UPLOAD_POST_IMAGE: NEXT_PUBLIC_UPLOAD_POST_IMAGE,
    UPLOAD_PERFIL_PRESET: NEXT_PUBLIC_UPLOAD_PERFIL_PRESET,
    PUBLIC_VAPID_KEY: NEXT_PUBLIC_PUBLIC_VAPID_KEY,
};

export const {
    DISQ,
    MEASUREMENT_ID,
    EDITOR_KEY,
    API_CLOUDIMARY,
    CLOUDINARY_APIKEY,
    CLOUDINARY_APISECRET,
    CLOUD_NAME,
    UPLOAD_PRESET,
    UPLOAD_POST_IMAGE,
    UPLOAD_PERFIL_PRESET,
    PUBLIC_VAPID_KEY,
} = env;
