export const allowRoutes = {
    "/dashboard/profile": "@perfil",
    "/dashboard/posts": "@post",
    "post-edit": "@post-edit",
    "/dashboard/tags": "@tag",
    "/dashboard/categories": "@categories",
    "/dashboard/admin/users": "@users",
    "/dashboard/admin/roles": "@roles",
    "roles-edit": "@roles-edit",
};

export const AllowedCheckData = {
    "@perfil": "a.perfil",
    "@post": "a.post",
    "@post-all": "a.post-all",
    "@post-create": "a.post-create",
    "@post-edit": "a.post-save",
    "@post-publish": "a.post-publish",
    "@post-delete": "a.post-delete",
    "@categories": "a.categories",
    "@categories-create": "a.categories-create",
    "@categories-edit": "a.categories-edit",
    "@categories-delete": "a.categories-delete",
    "@tag": "a.tag",
    "@tag-create": "a.tag-create",
    "@tag-edit": "a.tag-edit",
    "@tag-delete": "a.tag-delete",
    "@users": "a.users",
    "@users-create": "a.users-create",
    "@users-edit": "a.users-edit",
    "@users-delete": "a.users-delete",
    "@user-resource": "a.user-resource",
    "@roles": "a.roles",
    "@roles-create": "a.roles-create",
    "@roles-edit": "a.roles-edit",
    "@roles-delete": "a.roles-delete",
};

export const AllowedCheck = [
    {value: "@perfil", label: "a.perfil"},
    {
        label: "form.publicGroup",
        options: [
            {value: "@post", label: "a.post"},
            {value: "@post", label: "a.post-all"},
            {value: "@post-create", label: "a.post-create"},
            {value: "@post-edit", label: "a.post-save"},
            {value: "@post-publish", label: "a.post-publish"},
            {value: "@post-delete", label: "a.post-delete"},
            {value: "@categories", label: "a.categories"},
            {value: "@categories-create", label: "a.categories-create"},
            {value: "@categories-edit", label: "a.categories-edit"},
            {value: "@categories-delete", label: "a.categories-delete"},
            {value: "@tag", label: "a.tag"},
            {value: "@tag-create", label: "a.tag-create"},
            {value: "@tag-edit", label: "a.tag-edit"},
            {value: "@tag-delete", label: "a.tag-delete"},
        ],
    },
    {
        label: "form.adminGroup",
        options: [
            {value: "@users", label: "a.users"},
            {value: "@users-create", label: "a.users-create"},
            {value: "@users-edit", label: "a.users-edit"},
            {value: "@users-delete", label: "a.users-delete"},
            {value: "@user-resource", label: "a.user-resource"},
            {value: "@roles", label: "a.roles"},
            {value: "@roles-create", label: "a.roles-create"},
            {value: "@roles-edit", label: "a.roles-edit"},
            {value: "@roles-delete", label: "a.roles-delete"},
        ],
    },
];
